export default {
    WelcomeScreen: 'WelcomeScreen',

    BottomTabs: 'BottomTabs',
    LoggedStack: 'LoggedStack',
    NotLoggedStack: 'NotLoggedStack',

    HomeStack: 'HomeStack',
    HomeScreen: 'HomeScreen',
    CartScreen: 'CartScreen', 

    SearchStack: 'SearchStack',
    SearchScreen: 'SearchScreen',
    SearchCartScreen: 'SearchCartScreen',

    ChatStack: 'ChatStack',
    WelcomeChatScreen: 'WelcomeChatScreen',
    OfflineContactSupportScreen: 'OfflineContactSupportScreen',
    ChatScreen: 'ChatScreen',
    NewCallScreen: 'NewCallScreen',
    NewChatScreen: 'NewChatScreen',
    InvitationsScreen: 'InvitationsScreen',
    SnapfoodMapScreen: 'SnapfoodMapScreen',
    MyFriendsScreen: 'MyFriendsScreen',
    SnapfoodersScreen: 'SnapfoodersScreen',
    CallScreen: 'CallScreen',
    SnapfooderScreen : 'SnapfooderScreen',
    NewGroupScreen : 'NewGroupScreen',
    CreateGroupScreen : 'CreateGroupScreen',
    MessagesScreen : 'MessagesScreen',
    LocationPickupScreen : 'LocationPickupScreen',
    LocationMsgScreen : 'LocationMsgScreen',

    OrdersStack: 'OrdersStack',
    OrdersScreen: 'OrdersScreen',
    OrdersCartScreen: 'OrdersCartScreen',

    ProfileStack: 'ProfileStack',
    ProfileScreen: 'ProfileScreen',
    PhoneVerificationScreen: 'PhoneVerificationScreen',
    EditPhoneScreen: 'EditPhoneScreen', 
    ChangePasswordScreen: 'ChangePasswordScreen',
    FavouritesScreen: 'FavouritesScreen',
    AddressesScreen: 'AddressesScreen',  
    BlogScreen: 'BlogScreen',
    BlogDetailsScreen: 'BlogDetailsScreen',
    BlogFilterScreen : 'BlogFilterScreen',
    PromotionsScreen: 'PromotionsScreen',
    LoginScreen: 'LoginScreen',
    RegisterScreen: 'RegisterScreen',
    OnboardingScreen : 'OnboardingScreen',
    ForgotScreen: 'ForgotScreen',
    ResetPassScreen: 'ResetPassScreen',
    ResetPassDoneScreen: 'ResetPassDoneScreen',
    AlmostDoneScreen: 'AlmostDoneScreen',
    LocationSetupScreen: 'LocationSetupScreen',
    FilterScreen: 'FilterScreen',
    VendorScreen: 'VendorScreen',
    VendorLocationScreen: 'VendorLocationScreen',
    FoodScreen: 'FoodScreen',
    PastOrderScreen : 'PastOrderScreen',  
    NewAddressScreen : 'NewAddressScreen',
    AddressMapScreen : 'AddressMapScreen',
    CartPaymentScreen : 'CartPaymentScreen',
    CartSplitScreen : 'CartSplitScreen',
    SplitOrderScreen : 'SplitOrderScreen',
    SplitOrderNotuserScreen : 'SplitOrderNotuserScreen',
    OrderSummScreen : 'OrderSummScreen',
    OrderFilterScreen : 'OrderFilterScreen',
    TrackOrderScreen : 'TrackOrderScreen',
    OrderReviewScreen : 'OrderReviewScreen',
    SettingScreen : 'SettingScreen',
    WalletScreen : 'WalletScreen',
    InviteScreen : 'InviteScreen',
    ConfirmIdentityScreen : 'ConfirmIdentityScreen',
    PaymentMethodsScreen : 'PaymentMethodsScreen',
    NewCardScreen : 'NewCardScreen',
    ProfileEditScreen : 'ProfileEditScreen',
    SnapfoodersSplitScreen : 'SnapfoodersSplitScreen',
    PrivacyPolicyScreen : 'PrivacyPolicyScreen',
    TermsScreen : 'TermsScreen',
    SupportScreen : 'SupportScreen',
    BugReportScreen : 'BugReportScreen',
    AppVersionScreen : 'AppVersionScreen',
    AddListingScreen : 'AddListingScreen'
};

export const headerLessRoutes = [
    'LoginScreen',
    'RegisterScreen',
    'PhoneVerificationScreen',
    'EditPhoneScreen',
    'SearchScreen',  
];

export const bottomLessRoutes = [
    'LoginScreen',
    'RegisterScreen',
    'PhoneVerificationScreen',
    'EditPhoneScreen',
    'CartScreen',
    'SearchCartScreen',
    'OrdersCartScreen',
];
