export const APP = {
    SAFE_AREA_DIMENSIONS: 'SAFE_AREA_DIMENSIONS',
    SET_UNREVIEWED_ORDER: 'SET_UNREVIEWED_ORDER',
    CLOSE_REVIEW_MODAL: 'CLOSE_REVIEW_MODAL',

    GET_VENDORS_REQUEST: 'GET_VENDORS_REQUEST',
    GET_VENDORS_SUCCESS: 'GET_VENDORS_SUCCESS',
    GET_VENDORS_ERROR: 'GET_VENDORS_ERROR',
    UPDATE_VENDORS: 'UPDATE_VENDORS',

    GET_FEATURE_BLOCKS_REQUEST: 'GET_FEATURE_BLOCKS_REQUEST',
    GET_FEATURE_BLOCKS_SUCCESS: 'GET_FEATURE_BLOCKS_SUCCESS',
    GET_FEATURE_BLOCKS_ERROR: 'GET_FEATURE_BLOCKS_ERROR',

    GET_ADDRESSES_REQUEST: 'GET_ADDRESSES_REQUEST',
    GET_ADDRESSES_SUCCESS: 'GET_ADDRESSES_SUCCESS',
    GET_ADDRESSES_ERROR: 'GET_ADDRESSES_ERROR',
    UPDATE_ADDRESSES: 'UPDATE_ADDRESSES',

    DELETE_ADDRESSES_REQUEST: 'DELETE_ADDRESSES_REQUEST',
    DELETE_ADDRESSES_SUCCESS: 'DELETE_ADDRESSES_SUCCESS',
    DELETE_ADDRESSES_ERROR: 'DELETE_ADDRESSES_ERROR',

    GET_FAVOURITES_REQUEST: 'GET_FAVOURITES_REQUEST',
    GET_FAVOURITES_SUCCESS: 'GET_FAVOURITES_SUCCESS',
    GET_FAVOURITES_ERROR: 'GET_FAVOURITES_ERROR',

    CHANGE_FAVORITE_REQUEST: 'CHANGE_FAVORITE_REQUEST',
    CHANGE_FAVORITE_SUCCESS: 'CHANGE_FAVORITE_SUCCESS',
    CHANGE_FAVORITE_ERROR: 'CHANGE_FAVORITE_ERROR',

    SORT_VENDORS_BY_NAME: 'SORT_VENDORS_BY_NAME',
    SORT_VENDORS_BY_POPULARITY: 'SORT_VENDORS_BY_POPULARITY',
    SORT_VENDORS_BY_LOCATION: 'SORT_VENDORS_BY_LOCATION',
    APPLY_LOCATION: 'APPLY_LOCATION',
    APPLY_LOCATION_GEO: 'APPLY_LOCATION_GEO',
    CHECK_LOCATION: 'CHECK_LOCATION',
    RESET_BACK_TO_PARAM: 'RESET_BACK_TO_PARAM',
    FILL_CLOSED_MODAL_DATA: 'FILL_CLOSED_MODAL_DATA',
    RESET_CLOSED_MODAL_DATA: 'RESET_CLOSED_MODAL_DATA',

    GET_LAST_UNREVIEWED_ORDER_REQUEST: 'GET_LAST_UNREVIEWED_ORDER_REQUEST',
    GET_LAST_UNREVIEWED_ORDER_SUCCESS: 'GET_LAST_UNREVIEWED_ORDER_SUCCESS',
    GET_LAST_UNREVIEWED_ORDER_ERROR: 'GET_LAST_UNREVIEWED_ORDER_ERROR',

    SET_ADDRESS: 'SET_ADDRESS',

    GET_BANNERS: 'GET_BANNERS',
    GET_BANNERS_ERROR: 'GET_BANNERS_ERROR',
    GET_BANNERS_SUCCESS: 'GET_BANNERS_SUCCESS',
    SEND_BANNER_CLICKED: 'SEND_BANNER_CLICKED',

    SET_HASLOCATION_FLAG: 'SET_HASLOCATION_FLAG',

    LOGGED_IN: 'APP/LOGGED_IN',
    SEEN_ONBOARD: 'APP/SEEN_ONBOARD',
    USER_LOGGED_OUT: 'APP/USER_LOGGED_OUT',
    SET_USER_DATA: 'APP/SET_USER_DATA',
    SET_HAS_VERIFIED_PHONE: 'APP/SET_HAS_VERIFIED_PHONE',
    SET_LOCATION_DATA: 'APP/SET_LOCATION_DATA',
    SET_NEED_LOGIN : 'APP/SET_NEED_LOGIN',

    SHOW_ORDER_STATUS_MODAL : 'APP/SHOW_ORDER_STATUS_MODAL',
    SET_ACTIVE_SCREEN_FROM_PUSH : 'APP/SET_ACTIVE_SCREEN_FROM_PUSH',

    //CHAT
    SEND_MESSAGE: 'SEND_MESSAGE',
    ENTER_CHAT: 'ENTER_CHAT',
    INIT_CHAT_ROOM: 'INIT_CHAT_ROOM',
    INIT_CHAT_ROOM_STARTED: 'INIT_CHAT_ROOM_STARTED',
    CHAT_ROOM_EXIST: 'CHAT_ROOM_EXIST',
    INIT_CHAT_ROOM_SUCCESS: 'INIT_CHAT_ROOM_SUCCESS',
    INIT_CHAT_ROOM_ERROR: 'INIT_CHAT_ROOM_ERROR',
    NEW_MESSAGE_ARRIVED: 'NEW_MESSAGE_ARRIVED',
    MESSAGE_IS_MODIFIED: 'MESSAGE_IS_MODIFIED',
    SET_MESSAGES_SEEN: 'SET_MESSAGES_SEEN',
    BACK_TO_CHAT: 'BACK_TO_CHAT',

    INIT_CHANNEL_SUCCESS : 'INIT_CHANNEL_SUCCESS',
    SET_CHANNELS : 'SET_CHANNELS',

    
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    UPDATE_CART: 'UPDATE_CART',
      
    RESET_CART: 'RESET_CART',

    SET_FAVOURITES: 'SET_FAVOURITES',
    SET_ALL_FAVOURITES: 'SET_ALL_FAVOURITES',

    SET_ADDRESSES: 'SET_ADDRESSES',
    DELETED_ADDRESS: 'DELETED_ADDRESS',
    ADDED_ADDRESS: 'ADDED_ADDRESS',

    SET_DEFAULT_ORDERS_TAB : 'SET_DEFAULT_ORDERS_TAB',
    
    // CART
    ADD_ITEM_CART : 'ADD_ITEM_CART',
    REMOVE_ITEM_CART : 'REMOVE_ITEM_CART',
    SET_CART_SPLIT : 'SET_CART_SPLIT', 

    SET_CUTLERY_CART : 'SET_CUTLERY_CART',
    SET_COMMENT_CART : 'SET_COMMENT_CART',
    SET_COUPON_CART : 'SET_COUPON_CART',
    SET_PRICE_CART : 'SET_PRICE_CART',
    SET_DELIVERY_INFO_CART : 'SET_DELIVERY_INFO_CART',
    SET_PAYMENT_INFO_CART : 'SET_PAYMENT_INFO_CART',
 
    UPDATE_CART_ITEMS: 'UPDATE_CART_ITEMS',
    CLEAR_CART : 'CLEAR_CART',  
    SET_VENDOR_CART : 'SET_VENDOR_CART',
    SET_DEFAULT_DELIVERY_ADDRESS : 'SET_DEFAULT_DELIVERY_ADDRESS',

    // Global
    SET_INIT_HOME_TAB : 'set_init_home_tab',
    SET_HOMETAB_NAVIGATION : 'set_hometab_navigation', 
    TMP_PASS_CHANGED : 'pass_changed',
    TMP_ADDR_PICKED : 'location_address_picked',
    TMP_SET_FOOD : 'TMP_SET_FOOD',
    TMP_SET_ORDER : 'TMP_SET_ORDER',
    SET_VENDOR_FILTER : 'set_vendor_filter', 
    SET_VENDOR_SORT : 'set_vendor_sort', 
    SET_ORDERS_FILTER : 'set_orders_filter', 
    SET_LANG : 'SET_LANG',
    SET_PROFILE_BLOG_FILTER : 'SET_PROFILE_BLOG_FILTER',
    SET_BLOG_CATEGORIES : 'SET_BLOG_CATEGORIES',
};
