ENV['SWIFT_VERSION'] = '5' 

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Snapfood' do
  config = use_native_modules!

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'


  # comment the next line to disable credit card scanning
  pod 'CardIO' 

  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  target 'SnapfoodTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end