import { Dimensions, StyleSheet } from 'react-native';
import Theme from '../../../../theme';

const windowWidth = Dimensions.get('window').width;
const headerOffset = Theme.specifications.statusBarHeight + Theme.specifications.headerHeight;

export default StyleSheet.create({
    container: {
        flex: 1,
        marginTop: -headerOffset,
    },
    headerContainer: {
        flex: 1,
        flexDirection: 'row',
        zIndex: 10,
        position: 'absolute',
        top: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        width: windowWidth,
        height: Theme.specifications.headerHeight,
        marginTop: Theme.specifications.statusBarHeight,
    },
    headerLeftContainer: {
        flex: 3,
        width: windowWidth - 100,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerRightContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    iconContainer: {
        flex: 1,
        width: 35,
    },
    headerIcon: {
        width: 25,
        height: 25,
    },
    title: {
        color: Theme.colors.white,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 18,
    },
    categorySectionCategories: {
        backgroundColor: Theme.colors.white,
        paddingBottom: 10,
        paddingRight: 10,
        paddingTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
        zIndex: 20,
    },
    categoryTitle: {
        padding: 7,
        backgroundColor: Theme.colors.backgroundColor,
        color: Theme.colors.cyan1,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 13,
        marginRight: 5,
        borderTopLeftRadius: 4,
        borderTopRightRadius: 4,
        borderBottomLeftRadius: 4,
        borderBottomRightRadius: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    profileImage: {
        resizeMode: 'cover',
        marginTop: -50,
        marginRight: 10,
        borderTopLeftRadius: 4,
        borderTopRightRadius: 4,
        borderBottomLeftRadius: 4,
        borderBottomRightRadius: 4,
        zIndex: 1000,
        width: 80,
        height: 80,
    },
    description: {
        padding: 10,
        paddingBottom: 0,
        color: Theme.colors.gray3,
        fontFamily: 'SanFranciscoDisplay-Regular',
        fontSize: 15,
        textAlign: 'justify',
    },
    foodCategoryContainer: {
        padding: 5,
        marginTop: 10,
        marginBottom: -5,
        marginLeft: 10,
        borderTopWidth: 1,
        borderTopColor: Theme.colors.listBorderColor,
        borderBottomWidth: 1,
        borderBottomColor: Theme.colors.listBorderColor,
        backgroundColor: Theme.colors.backgroundColor,
    },
    foodInfoContainer: {
        padding: 5,
        marginLeft: 10,
    },
    foodContainer: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        paddingVertical: 5,
        borderBottomWidth: 1,
        borderBottomColor: Theme.colors.listBorderColor,
    },
    foodContainerSelected: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        paddingVertical: 5,
        borderBottomWidth: 1,
        borderBottomColor: Theme.colors.listBorderColor,
        borderLeftColor: Theme.colors.cyan2,
        borderLeftWidth: 4,
    },
    foodContainerLeft: {
        flex: 4,
    },
    foodContainerRight: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    foodCategory: {
        color: Theme.colors.black,
        fontFamily: 'SanFranciscoDisplay-Bold',
        fontSize: 18,
    },
    foodCategoryAv: {
        color: Theme.colors.black,
        fontFamily: 'SanFranciscoDisplay-Light',
        fontSize: 16,
    },
    foodTitle: {
        padding: 5,
        color: Theme.colors.gray1,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 15,
        textAlign: 'justify',
    },
    foodDesc: {
        padding: 5,
        paddingTop: 0,
        color: Theme.colors.gray1,
        fontFamily: 'SanFranciscoDisplay-Regular',
        fontSize: 13,
        textAlign: 'justify',
    },
    bottomContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    foodPreferred: {
        color: '#fe6a00',
        fontFamily: 'SanFranciscoDisplay-Regular',
        fontSize: 12,
        textAlign: 'justify',
        paddingLeft: 5,
    },
    starPreferred: {
        width: 12,
        height: 12,
        resizeMode: 'contain',
    },
    foodPrice: {
        paddingLeft: 5,
        color: Theme.colors.gray3,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 15,
    },
    foodImage: {
        width: 60,
        height: 60,
        resizeMode: 'contain',
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
        borderBottomLeftRadius: 8,
        borderBottomRightRadius: 8,
        overflow: 'hidden',
        borderRadius: 5,
    },
    orderAgain: {
        color: Theme.colors.black,
        fontFamily: 'SanFranciscoDisplay-Bold',
        fontSize: 18,
        paddingLeft: 10,
        paddingTop: 10,
    },
    orderAgainDesc: {
        color: Theme.colors.gray3,
        fontFamily: 'SanFranciscoDisplay-Regular',
        fontSize: 13,
        paddingLeft: 10,
    },
    ordersContainer: {
        margin: 10,
        marginBottom: 5,
        width: windowWidth - 50,
        padding: 10,
        backgroundColor: '#fff',
        borderRadius: 5,
    },
    ordersContainerTop: {
        flexDirection: 'row',
    },
    ordersContainerBottom: {
        paddingTop: 5,
        borderTopWidth: 1,
        borderTopColor: Theme.colors.listBorderColor,
        flexDirection: 'row',
        alignItems: 'center',
        alignContent: 'center',
    },
    ordersContainerBottomText: {
        color: Theme.colors.gray3,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 15,
    },
    ordersContainerLeft: {
        flex: 3,
    },
    ordersContainerLeftTitle: {
        color: Theme.colors.gray3,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 15,
    },
    ordersContainerLeftOptionTitle: {
        color: Theme.colors.gray3,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 12,
    },
    ordersContainerLeftPrice: {
        padding: 2,
        color: Theme.colors.gray3,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 15,
        justifyContent: 'flex-end',
    },
    ordersContainerLeftTop: {},
    ordersContainerLeftBottom: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    ordersContainerBottomImage: {
        marginTop: 2.5,
        width: 13,
        height: 13,
        resizeMode: 'contain',
    },
    ordersContainerRight: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    ordersContainerRightImage: {
        width: 70,
        height: 70,
        resizeMode: 'contain',
    },
    ordersContainerRightImagePrevious: {
        width: 40,
        height: 40,
        resizeMode: 'contain',
    },
    modal: {
        justifyContent: 'flex-end',
        margin: 0,
    },
    modalView: {
        backgroundColor: Theme.colors.white,
    },
    modalImageContainer: {
        width: windowWidth,
        height: 400,
        overflow: 'hidden',
        resizeMode: 'contain',
    },
    modalInfoContainer: {
        padding: 10,
        flexDirection: 'row',
    },
    modalInfoTitle: {
        color: Theme.colors.black,
        fontFamily: 'SanFranciscoDisplay-Medium',
        fontSize: 15,
    },
    modalInfoPrice: {
        color: Theme.colors.gray3,
        fontFamily: 'SanFranciscoDisplay-Regular',
        fontSize: 15,
        textAlign: 'right',
    },
    modalNrContainer: {
        padding: 20,
        paddingBottom: 30,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalNrImage: {
        width: 30,
        height: 30,
        resizeMode: 'contain',
    },
    button: {
        backgroundColor: Theme.colors.cyan2,
        margin: 30,
        marginTop: 15,
        padding: 10,
        justifyContent: 'center',
        alignItems: 'center',
        borderTopLeftRadius: 3,
        borderTopRightRadius: 3,
        borderBottomLeftRadius: 3,
        borderBottomRightRadius: 3,
    },
    buttonText: {
        fontFamily: 'SanFranciscoDisplay-Medium',
        color: Theme.colors.white,
        fontSize: 18,
        textAlign: 'center',
    },
    modal2: {
        flexDirection: 'row',
    },
    modal2Text: {
        fontFamily: 'SanFranciscoDisplay-Medium',
        color: Theme.colors.white,
        fontSize: 16,
    },
    footerImage: {
        width: 15,
        height: 15,
        resizeMode: 'contain',
    },
});